# Generated by Django 3.2.16 on 2023-04-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20230411_1839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='b_foodlist',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='b_ingredients',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='d_foodlist',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='d_ingredients',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='l_foodlist',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='l_ingredients',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='s_foodlist',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='s_ingredients',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='breakfast_foodlist',
            field=models.TextField(default='default_value'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='breakfast_ingredients',
            field=models.TextField(default='default_value'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='dinner_foodlist',
            field=models.TextField(default='default_value'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='dinner_ingredients',
            field=models.TextField(default='default_value'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='lunch_foodlist',
            field=models.TextField(default='default_value'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='lunch_ingredients',
            field=models.TextField(default='default_value'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='snacks_foodlist',
            field=models.TextField(default='default_value'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='snacks_ingredients',
            field=models.TextField(default='default_value'),
        ),
    ]
